In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_parquet("../data/sample.parquet")
df.head(100)

,fw,mver,lts,dst_name,af,dst_addr,src_addr,proto,ttl,size,...,min_value,max_value,avg_value,msm_id,prb_id,event_timestamp,msm_name,src_public_ip,measurement_type,step
0,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,29163287.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
1,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,128833857.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
2,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,67554090.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
3,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,86022645.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
4,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,29095968.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5090.0,2.6.4,62.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,20752023.0,7704.0,1.776102e+09,HTTPGet,2001:49f0:d00d:ff00::a,http,NaN
96,5090.0,2.6.4,62.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,159634556.0,7704.0,1.776102e+09,HTTPGet,2001:49f0:d00d:ff00::a,http,NaN
97,5090.0,2.6.4,65.0,2a00:1398:8:2::10,6.0,2a00:1398:8:2::10,2001:49f0:d00d:ff00::a,ICMP,NaN,48.0,...,NaN,NaN,NaN,17828885.0,7704.0,1.776102e+09,Traceroute,2001:49f0:d00d:ff00::a,traceroute,NaN
98,5090.0,2.6.4,45.0,212.202.68.1,4.0,212.202.68.1,107.162.220.5,ICMP,NaN,48.0,...,NaN,NaN,NaN,81236597.0,6451.0,1.776102e+09,Traceroute,107.162.220.5,traceroute,NaN
99,5090.0,2.6.4,35.0,156.154.85.254,4.0,156.154.85.254,107.162.220.5,ICMP,NaN,48.0,...,NaN,NaN,NaN,29743656.0,6451.0,1.776102e+09,Traceroute,107.162.220.5,traceroute,NaN

In [6]:
df.columns.tolist()

['fw',
 'mver',
 'lts',
 'dst_name',
 'af',
 'dst_addr',
 'src_addr',
 'proto',
 'ttl',
 'size',
 'dup',
 'rcvd',
 'sent',
 'min_value',
 'max_value',
 'avg_value',
 'msm_id',
 'prb_id',
 'event_timestamp',
 'msm_name',
 'src_public_ip',
 'measurement_type',
 'step']

In [7]:
df.head().T

,0,1,2,3,4
fw,5090.0,5090.0,5090.0,5090.0,5090.0
mver,2.6.4,2.6.4,2.6.4,2.6.4,2.6.4
lts,54.0,54.0,54.0,54.0,54.0
dst_name,None,None,None,None,None
af,NaN,NaN,NaN,NaN,NaN
dst_addr,None,None,None,None,None
src_addr,None,None,None,None,None
proto,None,None,None,None,None
ttl,NaN,NaN,NaN,NaN,NaN
size,NaN,NaN,NaN,NaN,NaN
dup,NaN,NaN,NaN,NaN,NaN
rcvd,NaN,NaN,NaN,NaN,NaN
sent,NaN,NaN,NaN,NaN,NaN
min_value,NaN,NaN,NaN,NaN,NaN
max_value,NaN,NaN,NaN,NaN,NaN
avg_value,NaN,NaN,NaN,NaN,NaN
msm_id,29163287.0,128833857.0,67554090.0,86022645.0,29095968.0
prb_id,6979.0,6979.0,6979.0,6979.0,6979.0
event_timestamp,1776101592.0,1776101592.0,1776101592.0,1776101592.0,1776101592.0
msm_name,HTTPGet,HTTPGet,HTTPGet,HTTPGet,HTTPGet
src_public_ip,2610:a1:3028:252::254,2610:a1:3028:252::254,2610:a1:3028:252::254,2610:a1:3028:252::254,2610:a1:3028:252::254
measurement_type,http,http,http,http,http
step,NaN,NaN,NaN,NaN,NaN