In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_parquet("../data/sample.parquet")
df.head(100)

,fw,mver,lts,dst_name,af,dst_addr,src_addr,proto,ttl,size,...,min_value,max_value,avg_value,msm_id,prb_id,event_timestamp,msm_name,src_public_ip,measurement_type,step
0,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,29163287.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
1,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,128833857.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
2,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,67554090.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
3,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,86022645.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
4,5090.0,2.6.4,54.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,29095968.0,6979.0,1.776102e+09,HTTPGet,2610:a1:3028:252::254,http,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5090.0,2.6.4,62.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,20752023.0,7704.0,1.776102e+09,HTTPGet,2001:49f0:d00d:ff00::a,http,NaN
96,5090.0,2.6.4,62.0,None,NaN,None,None,None,NaN,NaN,...,NaN,NaN,NaN,159634556.0,7704.0,1.776102e+09,HTTPGet,2001:49f0:d00d:ff00::a,http,NaN
97,5090.0,2.6.4,65.0,2a00:1398:8:2::10,6.0,2a00:1398:8:2::10,2001:49f0:d00d:ff00::a,ICMP,NaN,48.0,...,NaN,NaN,NaN,17828885.0,7704.0,1.776102e+09,Traceroute,2001:49f0:d00d:ff00::a,traceroute,NaN
98,5090.0,2.6.4,45.0,212.202.68.1,4.0,212.202.68.1,107.162.220.5,ICMP,NaN,48.0,...,NaN,NaN,NaN,81236597.0,6451.0,1.776102e+09,Traceroute,107.162.220.5,traceroute,NaN
99,5090.0,2.6.4,35.0,156.154.85.254,4.0,156.154.85.254,107.162.220.5,ICMP,NaN,48.0,...,NaN,NaN,NaN,29743656.0,6451.0,1.776102e+09,Traceroute,107.162.220.5,traceroute,NaN

In [6]:
df.columns.tolist()

['fw',
 'mver',
 'lts',
 'dst_name',
 'af',
 'dst_addr',
 'src_addr',
 'proto',
 'ttl',
 'size',
 'dup',
 'rcvd',
 'sent',
 'min_value',
 'max_value',
 'avg_value',
 'msm_id',
 'prb_id',
 'event_timestamp',
 'msm_name',
 'src_public_ip',
 'measurement_type',
 'step']

In [7]:
df.head().T

,0,1,2,3,4
fw,5090.0,5090.0,5090.0,5090.0,5090.0
mver,2.6.4,2.6.4,2.6.4,2.6.4,2.6.4
lts,54.0,54.0,54.0,54.0,54.0
dst_name,None,None,None,None,None
af,NaN,NaN,NaN,NaN,NaN
dst_addr,None,None,None,None,None
src_addr,None,None,None,None,None
proto,None,None,None,None,None
ttl,NaN,NaN,NaN,NaN,NaN
size,NaN,NaN,NaN,NaN,NaN
dup,NaN,NaN,NaN,NaN,NaN
rcvd,NaN,NaN,NaN,NaN,NaN
sent,NaN,NaN,NaN,NaN,NaN
min_value,NaN,NaN,NaN,NaN,NaN
max_value,NaN,NaN,NaN,NaN,NaN
avg_value,NaN,NaN,NaN,NaN,NaN
msm_id,29163287.0,128833857.0,67554090.0,86022645.0,29095968.0
prb_id,6979.0,6979.0,6979.0,6979.0,6979.0
event_timestamp,1776101592.0,1776101592.0,1776101592.0,1776101592.0,1776101592.0
msm_name,HTTPGet,HTTPGet,HTTPGet,HTTPGet,HTTPGet
src_public_ip,2610:a1:3028:252::254,2610:a1:3028:252::254,2610:a1:3028:252::254,2610:a1:3028:252::254,2610:a1:3028:252::254
measurement_type,http,http,http,http,http
step,NaN,NaN,NaN,NaN,NaN

In [8]:
df["measurement_type"].value_counts(dropna=False)

measurement_type
ping          7039
http          3265
traceroute    2617
dns           1837
sslcert         15
ntp              2
None             1
Name: count, dtype: int64

In [9]:
null_pct = df.isnull().mean().sort_values(ascending=False) * 100
null_pct

ttl                 63.799404
step                52.368706
avg_value           52.361938
dup                 52.361938
sent                52.361938
max_value           52.361938
min_value           52.361938
rcvd                52.361938
size                34.650785
dst_name            34.535734
src_addr            22.685436
dst_addr            22.604223
proto               22.570384
af                  22.468868
mver                 0.710612
fw                   0.006768
lts                  0.006768
prb_id               0.006768
msm_id               0.006768
event_timestamp      0.006768
msm_name             0.006768
src_public_ip        0.006768
measurement_type     0.006768
dtype: float64

In [11]:
for t in df["measurement_type"].dropna().unique():
    print("\nTYPE:", t)
    subset = df[df["measurement_type"] == t]
    print(subset.isnull().mean().sort_values().head(10))
    print(subset.isnull().mean().sort_values(ascending=False).head(10))

TYPE: http
fw                  0.000000
lts                 0.000000
measurement_type    0.000000
src_public_ip       0.000000
msm_name            0.000000
event_timestamp     0.000000
prb_id              0.000000
msm_id              0.000000
mver                0.001838
size                1.000000
dtype: float64
dst_addr     1.0
af           1.0
dst_name     1.0
src_addr     1.0
size         1.0
ttl          1.0
proto        1.0
avg_value    1.0
step         1.0
min_value    1.0
dtype: float64

TYPE: traceroute
fw                 0.0
lts                0.0
dst_name           0.0
af                 0.0
proto              0.0
size               0.0
prb_id             0.0
msm_id             0.0
msm_name           0.0
event_timestamp    0.0
dtype: float64
step         1.000000
max_value    1.000000
min_value    1.000000
rcvd         1.000000
sent         1.000000
dup          1.000000
ttl          1.000000
avg_value    1.000000
src_addr     0.005732
dst_addr     0.005732
dtype: float64

TYPE: ping
fw           0.0
lts          0.0
dst_name     0.0
af           0.0
proto        0.0
rcvd         0.0
dup          0.0
size         0.0
max_value    0.0
min_value    0.0
dtype: float64
ttl         0.240091
mver        0.007103
src_addr    0.000852
dst_addr    0.000710
step        0.000142
lts         0.000000
fw          0.000000
dst_name    0.000000
af          0.000000
size        0.000000
dtype: float64

TYPE: sslcert
fw                 0.0
lts                0.0
dst_name           0.0
af                 0.0
dst_addr           0.0
event_timestamp    0.0
prb_id             0.0
msm_id             0.0
msm_name           0.0
src_public_ip      0.0
dtype: float64
min_value    1.0
sent         1.0
rcvd         1.0
dup          1.0
size         1.0
ttl          1.0
proto        1.0
avg_value    1.0
step         1.0
max_value    1.0
dtype: float64

TYPE: dns
fw                  0.000000
lts                 0.000000
measurement_type    0.000000
src_public_ip       0.000000
msm_name            0.000000
event_timestamp     0.000000
prb_id              0.000000
msm_id              0.000000
mver                0.017964
dst_addr            0.029396
dtype: float64
dst_name     1.0
sent         1.0
min_value    1.0
rcvd         1.0
dup          1.0
size         1.0
ttl          1.0
step         1.0
avg_value    1.0
max_value    1.0
dtype: float64

TYPE: ntp
fw                 0.0
mver               0.0
lts                0.0
dst_name           0.0
af                 0.0
dst_addr           0.0
src_addr           0.0
proto              0.0
msm_name           0.0
event_timestamp    0.0
dtype: float64
max_value    1.0
sent         1.0
min_value    1.0
rcvd         1.0
dup          1.0
size         1.0
ttl          1.0
step         1.0
avg_value    1.0
af           0.0
dtype: float64